cc_binary(
    name = "day4",
    data = [
        ":input",
    ],
    copts = [
        "-std=c++17",
    ],
    srcs = [
        "day4.cpp",
    ],
    deps = [
        "//common/logging",
        "//common/string",
    ],
)

filegroup(
    name = "input",
    srcs = [
        "input.txt",
    ],
)
